# Site settings
title: EdoSec | 江戸sec
description: > # this means to ignore newlines until "baseurl:"
  Tokyo Security Professional Meetup | セキュリティの輪を広げよう
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://edos.ec"
twitter_username:    Edosec
facebook_username:   edosectokyo
github_username:     lincolnlogs
doorkeeper_username: edosec
linkedin_username:   
google_id:           
copyright: Forked from <a href="https://github.com/bhardin/silisec">Silisec</a>, munged by <a href="https://github.com/lincolnlogs/edosec">Lincolnlogs</a>
aldgate-jp: "http://www.the-aldgate.com/index2.htm"
aldgate-en: "http://www.the-aldgate.com/"
hobgoblin-jp: "http://www.hobgoblin.jp/Shibuya/tabid/120/language/ja-JP/Default.aspx"
hobgoblin-en: "http://www.hobgoblin.jp/shibuya/tabid/120/language/en-gb/default.aspx"
bulldog: "http://www.beer-bulldog.com/"

# Jekyll build settings
permalink: /meetup/:year/:title
exclude: [.gitignore, createPost.rb, CNAME, Gemfile, Gemfile.lock, README.md]
markdown: kramdown
